FROM ubuntu:16.04
LABEL Isaac A. White <iwhite@nagios.com>

RUN apt-get update && apt-get install -y sudo
RUN sudo apt-get update && \
    sudo apt-get install -y autoconf \
    gcc \
    make \
    apache2 \
    ufw \
    php \
    libc6 \
    libapache2-mod-php7.0 \
    libgd2-xpm-dev \
    libmcrypt-dev \
    libssl-dev \
    libnet-snmp-perl \
    wget \
    unzip \
    bc \
    gawk \
    dc \
    build-essential \
    snmp \
    gettext \
    supervisor \
    vim \
    git

RUN sudo dpkg -l selinux*
RUN sudo mkdir -p /var/www/html

