FROM ubuntu:16.04
LABEL Isaac A. White <iwhite@nagios.com>

RUN apt-get update && apt-get install -y sudo
RUN sudo apt-get update && \
    sudo apt-get install -y autoconf \
    gcc \
    make \
    apache2 \
    ufw \
    php \
    libc6 \
    libapache2-mod-php7.0 \
    libgd2-xpm-dev \
    libmcrypt-dev \
    libssl-dev \
    libnet-snmp-perl \
    wget \
    unzip \
    bc \
    gawk \
    dc \
    build-essential \
    snmp \
    gettext \
    supervisor \
    vim \
    git

RUN sudo dpkg -l selinux*
RUN sudo mkdir -p /var/www/html
COPY . /var/www/html/
WORKDIR /var/www/html/
RUN sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
RUN sudo make all

RUN sudo make install-groups-users
RUN sudo usermod -a -G nagios www-data

RUN sudo make install
RUN sudo make install-daemoninit
RUN sudo make install-commandmode
RUN sudo make install-config
RUN sudo make install-webconf
RUN sudo a2enmod rewrite
RUN sudo a2enmod cgi
#RUN sudo ufw allow Apache
#RUN sudo ufw reload

# Set the default password. Change the final argument to the password of choice.
RUN sudo htpasswd -bc /usr/local/nagios/etc/htpasswd.users nagiosadmin admin

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Open up valid ports to listen to outside of the container
EXPOSE 80 443 3306 3307 8000 8001 8002

RUN sudo mkdir -p /var/www/
WORKDIR /var/www/
RUN git clone https://github.com/nagios-plugins/nagios-plugins.git plugins
WORKDIR /var/www/plugins/
RUN sudo ./tools/setup
RUN sudo ./configure
RUN sudo make
RUN sudo make all
WORKDIR cd /var/www/html

RUN echo "alias dd='cd /var/www/html'" >> /root/.bash_profile

# Must be last line. This starts a persistent process that
CMD /usr/bin/supervisord -c /var/www/html/supervisord.conf
